# Generated by Django 4.2.3 on 2023-07-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spstaglib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spselement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='spselement',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='spselement',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
    ]
