# Generated by Django 4.1.7 on 2023-04-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spstaglib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="example",
            name="xml_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="xml_examples"),
        ),
    ]
