# Generated by Django 4.1.7 on 2023-04-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spstaglib", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Uma vez", max_length=256, verbose_name="Texto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Occurrence number",
                "verbose_name_plural": "Occurrence numbers",
            },
        ),
    ]
