# Generated by Django 4.1.7 on 2023-04-05 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spstaglib", "0003_example"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="example",
            name="xml_code",
        ),
    ]
