# Generated by Django 4.1.7 on 2023-04-05 20:12

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("spstaglib", "0004_remove_example_xml_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="xml_code",
            field=models.TextField(default="<article/>", verbose_name="XML Code"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="example",
            name="title",
            field=wagtail.fields.RichTextField(
                default="<article/>", verbose_name="Título"
            ),
            preserve_default=False,
        ),
    ]
