# Generated by Django 4.1.7 on 2023-04-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spstaglib", "0005_example_xml_code_alter_example_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="xml_code",
            field=models.ImageField(upload_to="xml_examples"),
        ),
    ]
