# Generated by Django 4.1.7 on 2023-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spstaglib", "0006_alter_example_xml_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="example",
            old_name="xml_code",
            new_name="xml_code_image",
        ),
        migrations.AddField(
            model_name="example",
            name="xml_code_text",
            field=models.TextField(blank=True, null=True, verbose_name="XML Code"),
        ),
    ]
